### ISSUE TITLE
cmake --build . produces error

### ISSUE THREAD

**Issue by qmeteor** [aws/aws-greengrass-core-sdk-c#2]
[Problem Description]:  Error after running `cmake --build .`
[Target OS/Architecture]: x86_64-apple-darwin17.7.0
[Greengrass Core Version]: 1.6.0
[Greengrass Core SDK for C Version]: 1.0.0
[Compiler and Version] : --with-gxx-include-dir=/usr/include/c++/4.2.1 Apple LLVM version 10.0.0
[Cmake Version] Cmake 3.12
[Logs] 
```
Scanning dependencies of target aws-greengrass-core-sdk-c
[ 50%] Building C object CMakeFiles/aws-greengrass-core-sdk-c.dir/lib/greengrasssdk.c.o
[100%] Linking C shared library libaws-greengrass-core-sdk-c.dylib
ld: unknown option: --version-script=/Users/project/aws-greengrass-core-sdk-c/version/greengrasssdk_versions.map
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libaws-greengrass-core-sdk-c.dylib] Error 1
make[1]: *** [CMakeFiles/aws-greengrass-core-sdk-c.dir/all] Error 2
make: *** [all] Error 2
```

I don't understand the error, please help me thanks.

**Comment by amzn-xyxu** [comment]
Hi qmeteor,

Thanks for using our Greengrass CSDK, the issue you saw is because you were trying to build your lambda on a MAC. I highly recommend you to build your executable lambda on the actually platform which your Greengrass Core will run on, so that you will not have cross-compilation issues. Also, I recommend you to to bring up your questions to our AWS Greengrass Forum: https://forums.aws.amazon.com/thread.jspa?threadID=246796, where you will get support from our engineers and also get help and share your questions with other developers in the community.

thanks,
Xiaoyang
